Rólunk oldalon discord link + leltár keresés és játékok helye
nyirit/jatszohaz.sch pull request #48
Opened 2022-01-10 17:55 UTC by hilite255

- A rólunk oldalra beraktam egy képet ami egy discord meghvó. Ez nem túl igényes, később meg lehetne csinálni szebbre, hogy kiírja a szerver nevét hányan vannak fent stb.
- A leltárban mostmár lehet név alapján keresni és most már a játékok helye is megjelenik.

2022-01-11 12:53 UTC, nyirit requested changes
Két apróság, amúgy jól néz ki! :)

2022-01-11 12:53 UTC, nyirit commented on jatszohaz/templates/static_pages/about_us.html
> +            </div>
Az invite link meddig érvényes? Nem fog pár héten belül lejárni?

Tabolás javítás:
```suggestion

    <div class="text-center">
    <br/><div style="float:left; width: 50%;" class="fb-page" data-href="https://www.facebook.com/SchJatszohaz/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/SchJatszohaz/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/SchJatszohaz/">Schönherz Játszóház</a></blockquote></div>
        <div style="display: inline-block; width: 30%; height: 130px; padding: 18px 0 0 0;">
            <a href="https://discord.gg/WS3VtB7ynP"><img src="../../static/img/Discord_Logo.png" width="100%" /></a>
        </div>
    </div>
```

2022-01-11 12:53 UTC, nyirit commented on jatszohaz/templates/inventory/list-inventory.html
> +            <div class="inventory_item_container" data-game-name="{{ game }}">
Amikor a játék nevében van nagybetű, a keresés sosem fogja kidobni, mivel a js kódban van egy `toLowerCase()` a keresett értékre, de nem a játékok neveire. Szerint vagy itt a template-ben lehet egy plusz `lower` filter (ld. lentebb), vagy a javascript kódban kell egy extra `toLowerCase()` hívás ennek a mezőnek az értékére.

```suggestion
            <div class="inventory_item_container" data-game-name="{{ game|lower }}">

```

2022-01-11 16:53 UTC, hilite255 commented on jatszohaz/templates/static_pages/about_us.html
> +            </div>
Elvileg olyan invite linket generáltattam ami nem jár le.

2022-01-12 17:50 UTC, nyirit approved these changes

2022-01-12 17:50 UTC, merged